### ISSUE TITLE
Regarding Development of Tutorial Docs in conda-tutorials repo 

### ISSUE THREAD

**Issue by Shreyas-SAS** [conda-incubator/conda-tutorial#1]
Hi @jezdez ,
I am Shreyas Sukhadeve, a technical writer who is targeting to get selected in Conda for GSoD'23, and wished to know if I could work on developing a tutorial on Conda if you do not have any prior plans for it. This would greatly help me strengthen my proposal for GSoD and understand Conda better. Can I work on this issue?

**Comment by ForgottenProgramme** [comment]
Hey, @Shreyas-SAS!
Thank you for your interest in contributing to conda, however this repository is not open for GSoD contributions.

**Comment by Shreyas-SAS** [comment]
Oh ok. Thanks, @ForgottenProgramme . I will contribute to conda through other means then. Also, best of luck for PyCon!
